# Generated by Django 4.1.7 on 2023-06-09 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_tabbitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tabbs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabb_name', models.CharField(max_length=100, verbose_name='Название')),
                ('tabb_text', models.TextField(default='Какой-то текст', max_length=500, verbose_name='Текст')),
            ],
        ),
        migrations.DeleteModel(
            name='TabbItem',
        ),
    ]
